export { addSeparator } from './add-separator';
export { camelize } from './camelize';
export { capitalize, capitalizeWords, capitalizeSentences } from './capitalize';
export { dasherize } from './dasherize';
export { deDasherize } from './de-dasherize';
export { humanize } from './humanize';
export { pluralize, pluralizeWithCount } from './pluralize';
export { regexMatchInGroups, matchGroup } from './regex-match-in-groups';
export { reverse } from './reverse';
export { toNumber } from './to-number';
export { trim } from './trim';
export { underscore } from './underscore';
