import {
  addDays,
  addYears,
  calculateAmountByFrequency,
  DayOfWeek,
  formatDate,
  formatStandardDate,
  Frequency,
  getHolidayDates,
  getHolidays,
  getIntervalFromFrequency,
  getLastDayOfYear,
  getNextBusinessDay,
  getNumberOfDaysInMonth,
  getNumberOfDaysInYear,
  getOntarioHolidays,
  getRecurringDates,
  getYearlyDates,
  isDayOfMonth,
  isDayOfWeek,
  isMonth,
  isRecurringTransactionSupportedFrequency,
  isValidCalendarDate,
  isValidDateString,
  isWeekend,
  Month,
  RECURRING_TRANSACTION_SUPPORTED_FREQUENCIES,
  RelativeTime,
  timeAgo,
  toCalendarDate,
  Week,
  withinXDays,
} from '.';

test('expors', () => {
  [
    addDays,
    addYears,
    calculateAmountByFrequency,
    formatDate, formatStandardDate,
    isValidCalendarDate,
    getHolidays, getOntarioHolidays, getHolidayDates,
    getIntervalFromFrequency,
    getLastDayOfYear,
    getNextBusinessDay,
    getNumberOfDaysInMonth,
    getNumberOfDaysInYear,
    getRecurringDates, isRecurringTransactionSupportedFrequency, RECURRING_TRANSACTION_SUPPORTED_FREQUENCIES,
    getYearlyDates,
    isValidDateString,
    isWeekend,
    timeAgo,
    toCalendarDate,
    withinXDays,
    DayOfWeek, Frequency, Month, RelativeTime, Week, isDayOfMonth, isDayOfWeek, isMonth,
  ].map(item => expect(item).toBeDefined());
});
