name: CI
on: [push]
jobs:
  build:
    name: Build, Lint, & Test Project
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 22.17.1 & setup the .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm run build
      - name: Run linter
        run: pnpm run lint
      - name: Run tests
        id: coverage
        run: |
          pnpm jest --coverage
          COVERAGE=$(cat ./coverage/coverage-summary.json | jq '.total.statements.pct')
          echo "Coverage: ${COVERAGE}%"
          echo "coverage=${COVERAGE}" >> $GITHUB_OUTPUT
